name: domotic-ai

services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: .
      target: prisma-migrate
    env_file:
      - ./.env.local

  init:
    container_name: init
    env_file:
      - ./.env.local
    build:
      context: .
      target: production
      args:
        - SERVICE_NAME=init
    restart: always
    depends_on:
      prisma-migrate:
        condition: service_completed_successfully

  api:
    container_name: api
    env_file:
      - ./.env.local
    build:
      context: .
      target: production
      args:
        - SERVICE_NAME=api
    restart: always
    expose:
      - 3003
    depends_on:
      init:
        condition: service_started

  mqtt-core:
    container_name: mqtt-core
    env_file:
      - ./.env.local
    build:
      context: .
      target: production
      args:
        - SERVICE_NAME=mqtt-core
    restart: always
    depends_on:
      init:
        condition: service_started

  rules-engine:
    container_name: rules-engine
    env_file:
      - ./.env.local
    build:
      context: .
      target: production
      args:
        - SERVICE_NAME=rules-engine
    restart: always
    depends_on:
      init:
        condition: service_started

  ai-service:
    container_name: ai-service
    env_file:
      - ./.env.local
    build:
      context: .
      target: production
      args:
        - SERVICE_NAME=ai-service
    restart: always
    depends_on:
      init:
        condition: service_started

networks:
  default:
    external: true
    name: domotic-network
